import { RedirectPage } from '@packages/daisy-ui-components';
import '@packages/daisy-ui-components/global.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

import './theme.css';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Car Sales',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
      <RedirectPage />
    </html>
  );
}
